# Scrabu Prototype (for a List of Shipment Numbers)

This notebook is for creating a prototype of the Scrabu project. The goal is to download DHL pages for a specific shipment number and scrap the shipment information from it.

#### Configure Logger

In [1]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.INFO, datefmt='%I:%M:%S')

#### Generate a list of shipment numbers

In [2]:
def generate_shipment_numbers(shipment_number=None, size=2): #340434188193324407
    logger.info("Generating shipment numbers with seed: {}".format(shipment_number))
    import numpy as np
    shipment_numbers_list = []
    for i in range(0, size):
        shipment_number_str = str(shipment_number).rjust(20, '0')
        shipment_numbers_list.append(shipment_number_str)
        shipment_number = shipment_number + 1
    logger.info("Generated {} unique shipment numbers".format(len(set(shipment_numbers_list))))
    return shipment_numbers_list

In [3]:
shipment_numbers = generate_shipment_numbers(shipment_number=340434188193323500, size=50)

05:07:48 INFO: Generating shipment numbers with seed: 340434188193323500
05:07:48 INFO: Generated 50 unique shipment numbers


#### Download the HTML content for a list of shipment numbers

In [4]:
def request(shipment_number=None, start_url="https://www.dhl.de/int-verfolgen/search?language=de&lang=de&domain=de&piececode="):
    import requests
    import numpy as np
    logger.debug("Making HTTP request for shipment number {}".format(shipment_number))
    request_url = start_url + str(shipment_number)
    return requests.get(request_url).content

In [5]:
html_response = request(shipment_number="00340434188193323500")

#### Parsing HTML and converting it into JSON

In [6]:
def html_to_json(html):
    from lxml import etree
    import json
    logger.debug("Converting HTML to JSON")
    
    html_tree = etree.HTML(html)
    
    def clean_json(dirty_json):
        start = dirty_json.find('JSON.parse(')
        end = dirty_json.find('"),', start)
        cjson = dirty_json[start:end]
        cjson = cjson.replace('JSON.parse("', '')
        cjson = cjson.replace('\\', '')
        return cjson
    
    def find_json_element(html_tree):
        json_element = html_tree.xpath('//div')
        return str(etree.tostring(json_element[0]))
    
    dirty_json = find_json_element(html_tree)
    json_string = clean_json(dirty_json)
    return json.loads(json_string)

In [7]:
shipment_details_json = html_to_json(html_response)

#### Structure the shipment details in JSON format

In [8]:
def shipment_details(shipment_details_json, start_url="https://www.dhl.de/int-verfolgen/search?language=de&lang=de&domain=de&piececode=", shipment_number="00340434188193323500"):
    import datetime
    logger.debug("Preparing JSON for persistance")
    delivery_history_dict = {}
    delivery_history_dict["shipment_number"] = shipment_details_json["sendungen"][0]["sendungsdetails"]["sendungsnummern"].get("sendungsnummer")
    delivery_history_dict["crawltime"] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    delivery_history_dict["url"] = start_url + str(shipment_number) 
    delivery_history_dict["events"] = shipment_details_json["sendungen"][0]["sendungsdetails"]["sendungsverlauf"].get("events", [])
    return delivery_history_dict

In [9]:
shipment_history = shipment_details(shipment_details_json)

In [10]:
import json
def save_dictionary(shipment_history=None, filename=None):
    logger.info("Writing file {}".format(filename))
    with open(filename, 'w') as f:
        json.dump(shipment_history, f)

In [11]:
save_dictionary(shipment_history=None, filename="../data/00340434188193323500.json")

05:07:49 INFO: Writing file ../data/00340434188193323500.json


#### Main function, which goes through all shipment numbers and uses the previous methods

In [25]:
import time
def main(shipment_number=None, size=None):
    shipment_numbers = generate_shipment_numbers(shipment_number=shipment_number, size=size)
    count_saved = 0
    start_index = 0
    found_index = []
    for shipment_number in shipment_numbers:
        time.sleep(0.5)
        html_response = request(shipment_number=shipment_number)
        shipment_details_json = html_to_json(html_response)
        shipment_history = shipment_details(shipment_details_json, shipment_number=shipment_number)
        if len(shipment_history['events']) > 0:
            save_dictionary(shipment_history, filename="../data/{}.json".format(shipment_number))
            count_saved = count_saved + 1
            found_index.append(start_index)
        else:
            logger.info("No events found for shipment number {}".format(shipment_number))
        start_index = start_index + 1
        print(found_index)
        import numpy as np
        print(np.diff(found_index))
    logger.info("Saved {} files out of {}".format(count_saved, size))
    

In [29]:
main(shipment_number=340434188193323500, size=400)

05:29:48 INFO: Generating shipment numbers with seed: 340434188193323500
05:29:48 INFO: Generated 400 unique shipment numbers
05:29:49 INFO: No events found for shipment number 00340434188193323500


[]
[]


05:29:50 INFO: No events found for shipment number 00340434188193323501


[]
[]


05:29:50 INFO: No events found for shipment number 00340434188193323502


[]
[]


05:29:51 INFO: No events found for shipment number 00340434188193323503


[]
[]


05:29:52 INFO: No events found for shipment number 00340434188193323504


[]
[]


05:29:52 INFO: No events found for shipment number 00340434188193323505


[]
[]


05:29:53 INFO: No events found for shipment number 00340434188193323506


[]
[]


05:29:53 INFO: No events found for shipment number 00340434188193323507


[]
[]


05:29:54 INFO: No events found for shipment number 00340434188193323508


[]
[]


05:29:55 INFO: Writing file ../data/00340434188193323509.json


[9]
[]


05:29:55 INFO: No events found for shipment number 00340434188193323510


[9]
[]


05:29:56 INFO: No events found for shipment number 00340434188193323511


[9]
[]


05:29:57 INFO: No events found for shipment number 00340434188193323512


[9]
[]


05:29:57 INFO: No events found for shipment number 00340434188193323513


[9]
[]


05:29:58 INFO: No events found for shipment number 00340434188193323514


[9]
[]


05:29:58 INFO: No events found for shipment number 00340434188193323515


[9]
[]


05:29:59 INFO: Writing file ../data/00340434188193323516.json


[9, 16]
[7]


05:30:00 INFO: No events found for shipment number 00340434188193323517


[9, 16]
[7]


05:30:00 INFO: No events found for shipment number 00340434188193323518


[9, 16]
[7]


05:30:01 INFO: No events found for shipment number 00340434188193323519


[9, 16]
[7]


05:30:02 INFO: No events found for shipment number 00340434188193323520


[9, 16]
[7]


05:30:02 INFO: No events found for shipment number 00340434188193323521


[9, 16]
[7]


05:30:03 INFO: No events found for shipment number 00340434188193323522


[9, 16]
[7]


05:30:04 INFO: Writing file ../data/00340434188193323523.json


[9, 16, 23]
[7 7]


05:30:04 INFO: No events found for shipment number 00340434188193323524


[9, 16, 23]
[7 7]


05:30:05 INFO: No events found for shipment number 00340434188193323525


[9, 16, 23]
[7 7]


05:30:06 INFO: No events found for shipment number 00340434188193323526


[9, 16, 23]
[7 7]


05:30:06 INFO: No events found for shipment number 00340434188193323527


[9, 16, 23]
[7 7]


05:30:07 INFO: No events found for shipment number 00340434188193323528


[9, 16, 23]
[7 7]


05:30:08 INFO: No events found for shipment number 00340434188193323529


[9, 16, 23]
[7 7]


05:30:08 INFO: Writing file ../data/00340434188193323530.json


[9, 16, 23, 30]
[7 7 7]


05:30:09 INFO: No events found for shipment number 00340434188193323531


[9, 16, 23, 30]
[7 7 7]


05:30:09 INFO: No events found for shipment number 00340434188193323532


[9, 16, 23, 30]
[7 7 7]


05:30:10 INFO: No events found for shipment number 00340434188193323533


[9, 16, 23, 30]
[7 7 7]


05:30:11 INFO: No events found for shipment number 00340434188193323534


[9, 16, 23, 30]
[7 7 7]


05:30:11 INFO: No events found for shipment number 00340434188193323535


[9, 16, 23, 30]
[7 7 7]


05:30:12 INFO: No events found for shipment number 00340434188193323536


[9, 16, 23, 30]
[7 7 7]


05:30:13 INFO: No events found for shipment number 00340434188193323537


[9, 16, 23, 30]
[7 7 7]


05:30:13 INFO: No events found for shipment number 00340434188193323538


[9, 16, 23, 30]
[7 7 7]


05:30:14 INFO: No events found for shipment number 00340434188193323539


[9, 16, 23, 30]
[7 7 7]


05:30:15 INFO: No events found for shipment number 00340434188193323540


[9, 16, 23, 30]
[7 7 7]


05:30:15 INFO: No events found for shipment number 00340434188193323541


[9, 16, 23, 30]
[7 7 7]


05:30:16 INFO: No events found for shipment number 00340434188193323542


[9, 16, 23, 30]
[7 7 7]


05:30:16 INFO: No events found for shipment number 00340434188193323543


[9, 16, 23, 30]
[7 7 7]


05:30:17 INFO: No events found for shipment number 00340434188193323544


[9, 16, 23, 30]
[7 7 7]


05:30:18 INFO: No events found for shipment number 00340434188193323545


[9, 16, 23, 30]
[7 7 7]


05:30:18 INFO: No events found for shipment number 00340434188193323546


[9, 16, 23, 30]
[7 7 7]


05:30:19 INFO: Writing file ../data/00340434188193323547.json


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:20 INFO: No events found for shipment number 00340434188193323548


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:20 INFO: No events found for shipment number 00340434188193323549


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:21 INFO: No events found for shipment number 00340434188193323550


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:22 INFO: No events found for shipment number 00340434188193323551


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:22 INFO: No events found for shipment number 00340434188193323552


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:23 INFO: No events found for shipment number 00340434188193323553


[9, 16, 23, 30, 47]
[ 7  7  7 17]


05:30:24 INFO: Writing file ../data/00340434188193323554.json


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:24 INFO: No events found for shipment number 00340434188193323555


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:25 INFO: No events found for shipment number 00340434188193323556


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:25 INFO: No events found for shipment number 00340434188193323557


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:26 INFO: No events found for shipment number 00340434188193323558


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:27 INFO: No events found for shipment number 00340434188193323559


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:27 INFO: No events found for shipment number 00340434188193323560


[9, 16, 23, 30, 47, 54]
[ 7  7  7 17  7]


05:30:28 INFO: Writing file ../data/00340434188193323561.json


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:29 INFO: No events found for shipment number 00340434188193323562


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:29 INFO: No events found for shipment number 00340434188193323563


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:30 INFO: No events found for shipment number 00340434188193323564


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:30 INFO: No events found for shipment number 00340434188193323565


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:31 INFO: No events found for shipment number 00340434188193323566


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:32 INFO: No events found for shipment number 00340434188193323567


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:32 INFO: No events found for shipment number 00340434188193323568


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:33 INFO: No events found for shipment number 00340434188193323569


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:33 INFO: No events found for shipment number 00340434188193323570


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:34 INFO: No events found for shipment number 00340434188193323571


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:35 INFO: No events found for shipment number 00340434188193323572


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:35 INFO: No events found for shipment number 00340434188193323573


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:36 INFO: No events found for shipment number 00340434188193323574


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:37 INFO: No events found for shipment number 00340434188193323575


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:37 INFO: No events found for shipment number 00340434188193323576


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:38 INFO: No events found for shipment number 00340434188193323577


[9, 16, 23, 30, 47, 54, 61]
[ 7  7  7 17  7  7]


05:30:39 INFO: Writing file ../data/00340434188193323578.json


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:39 INFO: No events found for shipment number 00340434188193323579


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:40 INFO: No events found for shipment number 00340434188193323580


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:40 INFO: No events found for shipment number 00340434188193323581


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:41 INFO: No events found for shipment number 00340434188193323582


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:42 INFO: No events found for shipment number 00340434188193323583


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:42 INFO: No events found for shipment number 00340434188193323584


[9, 16, 23, 30, 47, 54, 61, 78]
[ 7  7  7 17  7  7 17]


05:30:43 INFO: Writing file ../data/00340434188193323585.json


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:44 INFO: No events found for shipment number 00340434188193323586


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:44 INFO: No events found for shipment number 00340434188193323587


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:45 INFO: No events found for shipment number 00340434188193323588


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:46 INFO: No events found for shipment number 00340434188193323589


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:46 INFO: No events found for shipment number 00340434188193323590


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:47 INFO: No events found for shipment number 00340434188193323591


[9, 16, 23, 30, 47, 54, 61, 78, 85]
[ 7  7  7 17  7  7 17  7]


05:30:48 INFO: Writing file ../data/00340434188193323592.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:48 INFO: No events found for shipment number 00340434188193323593


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:49 INFO: No events found for shipment number 00340434188193323594


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:50 INFO: No events found for shipment number 00340434188193323595


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:50 INFO: No events found for shipment number 00340434188193323596


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:51 INFO: No events found for shipment number 00340434188193323597


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:52 INFO: No events found for shipment number 00340434188193323598


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:52 INFO: No events found for shipment number 00340434188193323599


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:53 INFO: No events found for shipment number 00340434188193323600


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:54 INFO: No events found for shipment number 00340434188193323601


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:54 INFO: No events found for shipment number 00340434188193323602


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:55 INFO: No events found for shipment number 00340434188193323603


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:55 INFO: No events found for shipment number 00340434188193323604


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:56 INFO: No events found for shipment number 00340434188193323605


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:57 INFO: No events found for shipment number 00340434188193323606


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:57 INFO: No events found for shipment number 00340434188193323607


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92]
[ 7  7  7 17  7  7 17  7  7]


05:30:58 INFO: Writing file ../data/00340434188193323608.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:30:59 INFO: No events found for shipment number 00340434188193323609


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:30:59 INFO: No events found for shipment number 00340434188193323610


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:31:00 INFO: No events found for shipment number 00340434188193323611


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:31:00 INFO: No events found for shipment number 00340434188193323612


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:31:01 INFO: No events found for shipment number 00340434188193323613


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:31:02 INFO: No events found for shipment number 00340434188193323614


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108]
[ 7  7  7 17  7  7 17  7  7 16]


05:31:02 INFO: Writing file ../data/00340434188193323615.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:03 INFO: No events found for shipment number 00340434188193323616


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:04 INFO: No events found for shipment number 00340434188193323617


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:04 INFO: No events found for shipment number 00340434188193323618


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:05 INFO: No events found for shipment number 00340434188193323619


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:05 INFO: No events found for shipment number 00340434188193323620


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:06 INFO: No events found for shipment number 00340434188193323621


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115]
[ 7  7  7 17  7  7 17  7  7 16  7]


05:31:07 INFO: Writing file ../data/00340434188193323622.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:07 INFO: No events found for shipment number 00340434188193323623


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:08 INFO: No events found for shipment number 00340434188193323624


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:09 INFO: No events found for shipment number 00340434188193323625


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:09 INFO: No events found for shipment number 00340434188193323626


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:10 INFO: No events found for shipment number 00340434188193323627


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:11 INFO: No events found for shipment number 00340434188193323628


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:11 INFO: No events found for shipment number 00340434188193323629


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:12 INFO: No events found for shipment number 00340434188193323630


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:13 INFO: No events found for shipment number 00340434188193323631


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:13 INFO: No events found for shipment number 00340434188193323632


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:14 INFO: No events found for shipment number 00340434188193323633


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:15 INFO: No events found for shipment number 00340434188193323634


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:15 INFO: No events found for shipment number 00340434188193323635


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:16 INFO: No events found for shipment number 00340434188193323636


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:16 INFO: No events found for shipment number 00340434188193323637


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:17 INFO: No events found for shipment number 00340434188193323638


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122]
[ 7  7  7 17  7  7 17  7  7 16  7  7]


05:31:18 INFO: Writing file ../data/00340434188193323639.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:18 INFO: No events found for shipment number 00340434188193323640


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:19 INFO: No events found for shipment number 00340434188193323641


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:20 INFO: No events found for shipment number 00340434188193323642


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:20 INFO: No events found for shipment number 00340434188193323643


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:21 INFO: No events found for shipment number 00340434188193323644


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:22 INFO: No events found for shipment number 00340434188193323645


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17]


05:31:22 INFO: Writing file ../data/00340434188193323646.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:23 INFO: No events found for shipment number 00340434188193323647


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:24 INFO: No events found for shipment number 00340434188193323648


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:24 INFO: No events found for shipment number 00340434188193323649


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:25 INFO: No events found for shipment number 00340434188193323650


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:25 INFO: No events found for shipment number 00340434188193323651


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:26 INFO: No events found for shipment number 00340434188193323652


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7]


05:31:27 INFO: Writing file ../data/00340434188193323653.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:27 INFO: No events found for shipment number 00340434188193323654


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:28 INFO: No events found for shipment number 00340434188193323655


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:29 INFO: No events found for shipment number 00340434188193323656


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:29 INFO: No events found for shipment number 00340434188193323657


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:30 INFO: No events found for shipment number 00340434188193323658


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:30 INFO: No events found for shipment number 00340434188193323659


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7]


05:31:31 INFO: Writing file ../data/00340434188193323660.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:32 INFO: No events found for shipment number 00340434188193323661


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:32 INFO: No events found for shipment number 00340434188193323662


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:33 INFO: No events found for shipment number 00340434188193323663


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:34 INFO: No events found for shipment number 00340434188193323664


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:34 INFO: No events found for shipment number 00340434188193323665


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:35 INFO: No events found for shipment number 00340434188193323666


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:36 INFO: No events found for shipment number 00340434188193323667


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:36 INFO: No events found for shipment number 00340434188193323668


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:37 INFO: No events found for shipment number 00340434188193323669


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:37 INFO: No events found for shipment number 00340434188193323670


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:38 INFO: No events found for shipment number 00340434188193323671


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:39 INFO: No events found for shipment number 00340434188193323672


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:39 INFO: No events found for shipment number 00340434188193323673


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:40 INFO: No events found for shipment number 00340434188193323674


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:41 INFO: No events found for shipment number 00340434188193323675


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:41 INFO: No events found for shipment number 00340434188193323676


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7]


05:31:42 INFO: Writing file ../data/00340434188193323677.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:43 INFO: No events found for shipment number 00340434188193323678


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:43 INFO: No events found for shipment number 00340434188193323679


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:44 INFO: No events found for shipment number 00340434188193323680


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:44 INFO: No events found for shipment number 00340434188193323681


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:45 INFO: No events found for shipment number 00340434188193323682


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:46 INFO: No events found for shipment number 00340434188193323683


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17]


05:31:46 INFO: Writing file ../data/00340434188193323684.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:47 INFO: No events found for shipment number 00340434188193323685


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:48 INFO: No events found for shipment number 00340434188193323686


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:48 INFO: No events found for shipment number 00340434188193323687


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:49 INFO: No events found for shipment number 00340434188193323688


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:50 INFO: No events found for shipment number 00340434188193323689


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:50 INFO: No events found for shipment number 00340434188193323690


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7]


05:31:51 INFO: Writing file ../data/00340434188193323691.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:51 INFO: No events found for shipment number 00340434188193323692


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:52 INFO: No events found for shipment number 00340434188193323693


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:53 INFO: No events found for shipment number 00340434188193323694


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:54 INFO: No events found for shipment number 00340434188193323695


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:54 INFO: No events found for shipment number 00340434188193323696


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:55 INFO: No events found for shipment number 00340434188193323697


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:55 INFO: No events found for shipment number 00340434188193323698


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:56 INFO: No events found for shipment number 00340434188193323699


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:57 INFO: No events found for shipment number 00340434188193323700


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:57 INFO: No events found for shipment number 00340434188193323701


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:58 INFO: No events found for shipment number 00340434188193323702


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:59 INFO: No events found for shipment number 00340434188193323703


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:31:59 INFO: No events found for shipment number 00340434188193323704


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:32:00 INFO: No events found for shipment number 00340434188193323705


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:32:00 INFO: No events found for shipment number 00340434188193323706


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7]


05:32:01 INFO: Writing file ../data/00340434188193323707.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:02 INFO: No events found for shipment number 00340434188193323708


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:03 INFO: No events found for shipment number 00340434188193323709


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:03 INFO: No events found for shipment number 00340434188193323710


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:04 INFO: No events found for shipment number 00340434188193323711


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:05 INFO: No events found for shipment number 00340434188193323712


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:05 INFO: No events found for shipment number 00340434188193323713


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16]


05:32:06 INFO: Writing file ../data/00340434188193323714.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:07 INFO: No events found for shipment number 00340434188193323715


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:07 INFO: No events found for shipment number 00340434188193323716


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:08 INFO: No events found for shipment number 00340434188193323717


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:08 INFO: No events found for shipment number 00340434188193323718


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:09 INFO: No events found for shipment number 00340434188193323719


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:10 INFO: No events found for shipment number 00340434188193323720


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7]


05:32:10 INFO: Writing file ../data/00340434188193323721.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:11 INFO: No events found for shipment number 00340434188193323722


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:12 INFO: No events found for shipment number 00340434188193323723


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:12 INFO: No events found for shipment number 00340434188193323724


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:13 INFO: No events found for shipment number 00340434188193323725


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:14 INFO: No events found for shipment number 00340434188193323726


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:14 INFO: No events found for shipment number 00340434188193323727


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:15 INFO: No events found for shipment number 00340434188193323728


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:16 INFO: No events found for shipment number 00340434188193323729


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:16 INFO: No events found for shipment number 00340434188193323730


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:17 INFO: No events found for shipment number 00340434188193323731


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:18 INFO: No events found for shipment number 00340434188193323732


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:18 INFO: No events found for shipment number 00340434188193323733


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:19 INFO: No events found for shipment number 00340434188193323734


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:19 INFO: No events found for shipment number 00340434188193323735


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:20 INFO: No events found for shipment number 00340434188193323736


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:21 INFO: No events found for shipment number 00340434188193323737


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7]


05:32:21 INFO: Writing file ../data/00340434188193323738.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:22 INFO: No events found for shipment number 00340434188193323739


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:23 INFO: No events found for shipment number 00340434188193323740


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:23 INFO: No events found for shipment number 00340434188193323741


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:24 INFO: No events found for shipment number 00340434188193323742


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:25 INFO: No events found for shipment number 00340434188193323743


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:25 INFO: No events found for shipment number 00340434188193323744


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17]


05:32:26 INFO: Writing file ../data/00340434188193323745.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:27 INFO: No events found for shipment number 00340434188193323746


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:27 INFO: No events found for shipment number 00340434188193323747


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:28 INFO: No events found for shipment number 00340434188193323748


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:28 INFO: No events found for shipment number 00340434188193323749


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:29 INFO: No events found for shipment number 00340434188193323750


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:30 INFO: No events found for shipment number 00340434188193323751


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7]


05:32:30 INFO: Writing file ../data/00340434188193323752.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:31 INFO: No events found for shipment number 00340434188193323753


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:32 INFO: No events found for shipment number 00340434188193323754


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:32 INFO: No events found for shipment number 00340434188193323755


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:33 INFO: No events found for shipment number 00340434188193323756


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:34 INFO: No events found for shipment number 00340434188193323757


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:34 INFO: No events found for shipment number 00340434188193323758


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:35 INFO: No events found for shipment number 00340434188193323759


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:36 INFO: No events found for shipment number 00340434188193323760


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:36 INFO: No events found for shipment number 00340434188193323761


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:37 INFO: No events found for shipment number 00340434188193323762


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:38 INFO: No events found for shipment number 00340434188193323763


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:38 INFO: No events found for shipment number 00340434188193323764


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:39 INFO: No events found for shipment number 00340434188193323765


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:39 INFO: No events found for shipment number 00340434188193323766


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:40 INFO: No events found for shipment number 00340434188193323767


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:41 INFO: No events found for shipment number 00340434188193323768


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7]


05:32:41 INFO: Writing file ../data/00340434188193323769.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:42 INFO: No events found for shipment number 00340434188193323770


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:43 INFO: No events found for shipment number 00340434188193323771


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:43 INFO: No events found for shipment number 00340434188193323772


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:44 INFO: No events found for shipment number 00340434188193323773


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:44 INFO: No events found for shipment number 00340434188193323774


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:45 INFO: No events found for shipment number 00340434188193323775


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17]


05:32:46 INFO: Writing file ../data/00340434188193323776.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:46 INFO: No events found for shipment number 00340434188193323777


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:47 INFO: No events found for shipment number 00340434188193323778


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:48 INFO: No events found for shipment number 00340434188193323779


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:48 INFO: No events found for shipment number 00340434188193323780


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:49 INFO: No events found for shipment number 00340434188193323781


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:50 INFO: No events found for shipment number 00340434188193323782


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7]


05:32:50 INFO: Writing file ../data/00340434188193323783.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:51 INFO: No events found for shipment number 00340434188193323784


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:52 INFO: No events found for shipment number 00340434188193323785


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:52 INFO: No events found for shipment number 00340434188193323786


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:53 INFO: No events found for shipment number 00340434188193323787


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:54 INFO: No events found for shipment number 00340434188193323788


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:54 INFO: No events found for shipment number 00340434188193323789


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7]


05:32:55 INFO: Writing file ../data/00340434188193323790.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:56 INFO: No events found for shipment number 00340434188193323791


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:57 INFO: No events found for shipment number 00340434188193323792


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:57 INFO: No events found for shipment number 00340434188193323793


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:58 INFO: No events found for shipment number 00340434188193323794


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:59 INFO: No events found for shipment number 00340434188193323795


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:32:59 INFO: No events found for shipment number 00340434188193323796


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:00 INFO: No events found for shipment number 00340434188193323797


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:01 INFO: No events found for shipment number 00340434188193323798


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:01 INFO: No events found for shipment number 00340434188193323799


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:02 INFO: No events found for shipment number 00340434188193323800


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:02 INFO: No events found for shipment number 00340434188193323801


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:03 INFO: No events found for shipment number 00340434188193323802


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:04 INFO: No events found for shipment number 00340434188193323803


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:04 INFO: No events found for shipment number 00340434188193323804


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:05 INFO: No events found for shipment number 00340434188193323805


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7]


05:33:06 INFO: Writing file ../data/00340434188193323806.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:06 INFO: No events found for shipment number 00340434188193323807


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:07 INFO: No events found for shipment number 00340434188193323808


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:08 INFO: No events found for shipment number 00340434188193323809


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:08 INFO: No events found for shipment number 00340434188193323810


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:09 INFO: No events found for shipment number 00340434188193323811


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:10 INFO: No events found for shipment number 00340434188193323812


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16]


05:33:10 INFO: Writing file ../data/00340434188193323813.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:11 INFO: No events found for shipment number 00340434188193323814


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:12 INFO: No events found for shipment number 00340434188193323815


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:12 INFO: No events found for shipment number 00340434188193323816


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:13 INFO: No events found for shipment number 00340434188193323817


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:14 INFO: No events found for shipment number 00340434188193323818


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:14 INFO: No events found for shipment number 00340434188193323819


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7]


05:33:15 INFO: Writing file ../data/00340434188193323820.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:16 INFO: No events found for shipment number 00340434188193323821


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:16 INFO: No events found for shipment number 00340434188193323822


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:17 INFO: No events found for shipment number 00340434188193323823


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:18 INFO: No events found for shipment number 00340434188193323824


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:18 INFO: No events found for shipment number 00340434188193323825


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:19 INFO: No events found for shipment number 00340434188193323826


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:20 INFO: No events found for shipment number 00340434188193323827


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:21 INFO: No events found for shipment number 00340434188193323828


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:21 INFO: No events found for shipment number 00340434188193323829


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:22 INFO: No events found for shipment number 00340434188193323830


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:23 INFO: No events found for shipment number 00340434188193323831


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:23 INFO: No events found for shipment number 00340434188193323832


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:24 INFO: No events found for shipment number 00340434188193323833


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:24 INFO: No events found for shipment number 00340434188193323834


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:25 INFO: No events found for shipment number 00340434188193323835


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:26 INFO: No events found for shipment number 00340434188193323836


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7]


05:33:27 INFO: Writing file ../data/00340434188193323837.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:27 INFO: No events found for shipment number 00340434188193323838


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:28 INFO: No events found for shipment number 00340434188193323839


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:28 INFO: No events found for shipment number 00340434188193323840


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:29 INFO: No events found for shipment number 00340434188193323841


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:30 INFO: No events found for shipment number 00340434188193323842


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:30 INFO: No events found for shipment number 00340434188193323843


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17]


05:33:31 INFO: Writing file ../data/00340434188193323844.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:32 INFO: No events found for shipment number 00340434188193323845


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:32 INFO: No events found for shipment number 00340434188193323846


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:33 INFO: No events found for shipment number 00340434188193323847


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:34 INFO: No events found for shipment number 00340434188193323848


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:34 INFO: No events found for shipment number 00340434188193323849


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:35 INFO: No events found for shipment number 00340434188193323850


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7]


05:33:36 INFO: Writing file ../data/00340434188193323851.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:36 INFO: No events found for shipment number 00340434188193323852


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:37 INFO: No events found for shipment number 00340434188193323853


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:37 INFO: No events found for shipment number 00340434188193323854


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:38 INFO: No events found for shipment number 00340434188193323855


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:39 INFO: No events found for shipment number 00340434188193323856


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:39 INFO: No events found for shipment number 00340434188193323857


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:40 INFO: No events found for shipment number 00340434188193323858


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:41 INFO: No events found for shipment number 00340434188193323859


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:41 INFO: No events found for shipment number 00340434188193323860


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:42 INFO: No events found for shipment number 00340434188193323861


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:42 INFO: No events found for shipment number 00340434188193323862


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:43 INFO: No events found for shipment number 00340434188193323863


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:44 INFO: No events found for shipment number 00340434188193323864


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:44 INFO: No events found for shipment number 00340434188193323865


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:45 INFO: No events found for shipment number 00340434188193323866


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:46 INFO: No events found for shipment number 00340434188193323867


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7]


05:33:46 INFO: Writing file ../data/00340434188193323868.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:47 INFO: No events found for shipment number 00340434188193323869


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:48 INFO: No events found for shipment number 00340434188193323870


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:48 INFO: No events found for shipment number 00340434188193323871


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:49 INFO: No events found for shipment number 00340434188193323872


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:49 INFO: No events found for shipment number 00340434188193323873


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:50 INFO: No events found for shipment number 00340434188193323874


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17]


05:33:51 INFO: Writing file ../data/00340434188193323875.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:52 INFO: No events found for shipment number 00340434188193323876


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:52 INFO: No events found for shipment number 00340434188193323877


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:53 INFO: No events found for shipment number 00340434188193323878


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:53 INFO: No events found for shipment number 00340434188193323879


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:54 INFO: No events found for shipment number 00340434188193323880


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:55 INFO: No events found for shipment number 00340434188193323881


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7]


05:33:55 INFO: Writing file ../data/00340434188193323882.json


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:56 INFO: No events found for shipment number 00340434188193323883


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:57 INFO: No events found for shipment number 00340434188193323884


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:57 INFO: No events found for shipment number 00340434188193323885


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:58 INFO: No events found for shipment number 00340434188193323886


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:58 INFO: No events found for shipment number 00340434188193323887


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:33:59 INFO: No events found for shipment number 00340434188193323888


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:00 INFO: No events found for shipment number 00340434188193323889


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:00 INFO: No events found for shipment number 00340434188193323890


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:01 INFO: No events found for shipment number 00340434188193323891


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:02 INFO: No events found for shipment number 00340434188193323892


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:02 INFO: No events found for shipment number 00340434188193323893


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:03 INFO: No events found for shipment number 00340434188193323894


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:03 INFO: No events found for shipment number 00340434188193323895


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:04 INFO: No events found for shipment number 00340434188193323896


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:05 INFO: No events found for shipment number 00340434188193323897


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:05 INFO: No events found for shipment number 00340434188193323898


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7]


05:34:06 INFO: Writing file ../data/00340434188193323899.json
05:34:06 INFO: Saved 40 files out of 400


[9, 16, 23, 30, 47, 54, 61, 78, 85, 92, 108, 115, 122, 139, 146, 153, 160, 177, 184, 191, 207, 214, 221, 238, 245, 252, 269, 276, 283, 290, 306, 313, 320, 337, 344, 351, 368, 375, 382, 399]
[ 7  7  7 17  7  7 17  7  7 16  7  7 17  7  7  7 17  7  7 16  7  7 17  7
  7 17  7  7  7 16  7  7 17  7  7 17  7  7 17]
